### ISSUE TITLE
The bot is running but didnt play the stream

### ISSUE THREAD

**Issue by Extrimist09** [FabiChan99/24-7-discord-radio#1]
The error look like this
24/7 Radio is Ready
WEBSOCKET | Connection Failure:: 400, message='Invalid response status', url=URL('ws://34.120.194.28:443')
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/wavelink/websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 400, message='Invalid response status', url=URL('ws://34.120.194.28:443')
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<radio() done, defined at /home/runner/24-7-discord-radio/Cogs/radiomodule.py:30> exception=ZeroConnectedNodes()>
Traceback (most recent call last):
  File "/home/runner/24-7-discord-radio/Cogs/radiomodule.py", line 38, in radio
    tracks = await self.bot.wavelink.get_tracks(self.radio)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/wavelink/client.py", line 165, in get_tracks
    raise ZeroConnectedNodes
wavelink.errors.ZeroConnectedNodes

**Comment by fthomys** [comment]
Are you sure that u are running a Lavalink Server on Port 2333?

**Comment by fthomys** [comment]
Does it work?
